
INSERT INTO public.stories (title, slug, author, description, cover_url, genres, status, total_chapters, view_count, is_featured) VALUES ('Kiếm Thần Trở Lại', 'kiem-than-tro-lai', 'Vô Danh Tiểu Tốt', 'Sau ngàn năm phong ấn, kiếm thần Lâm Phong trở lại nhân gian với một cơ thể phàm nhân. Con đường phục hận và tìm lại vinh quang xưa bắt đầu từ ngôi làng nhỏ nơi hắn được tái sinh…', 'https://images.unsplash.com/photo-1541963463532-d68292c34b19?w=600&h=800&fit=crop', ARRAY['Huyền huyễn','Hành động']::TEXT[], 'ongoing', 20, 1240000, true) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.stories (title, slug, author, description, cover_url, genres, status, total_chapters, view_count, is_featured) VALUES ('Tình Yêu Mùa Hoa Anh Đào', 'tinh-yeu-mua-hoa-anh-dao', 'Sakura Yuki', 'Một câu chuyện thanh xuân dịu dàng giữa cô nữ sinh trầm lặng và chàng lớp trưởng lạnh lùng, bắt đầu từ một cánh hoa anh đào rơi trên trang vở…', 'https://images.unsplash.com/photo-1519681393784-d120267933ba?w=600&h=800&fit=crop', ARRAY['Lãng mạn','Học đường']::TEXT[], 'ongoing', 20, 890000, true) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.stories (title, slug, author, description, cover_url, genres, status, total_chapters, view_count, is_featured) VALUES ('Hệ Thống Vô Hạn', 'he-thong-vo-han', 'Code Master', 'Bị hệ thống chọn làm người chơi, Trần Vũ phải chinh phục vô số thế giới song song để tồn tại. Mỗi lần chết là một lần tái sinh, mỗi thử thách là một bước tiến…', 'https://images.unsplash.com/photo-1531306728370-e2ebd9d7bb99?w=600&h=800&fit=crop', ARRAY['Khoa huyễn','Phiêu lưu']::TEXT[], 'ongoing', 20, 2100000, true) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.stories (title, slug, author, description, cover_url, genres, status, total_chapters, view_count, is_featured) VALUES ('Tôi Nghe Nói Cậu Yêu Tôi', 'toi-nghe-noi-cau-yeu-toi', 'Minh Nguyệt', 'Cô gái vô tình nghe lỏm được lời tỏ tình của chàng trai nổi tiếng nhất trường. Rắc rối là — lời đó không dành cho cô…', 'https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=600&h=800&fit=crop', ARRAY['Lãng mạn','Hài hước']::TEXT[], 'completed', 20, 670000, true) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.stories (title, slug, author, description, cover_url, genres, status, total_chapters, view_count, is_featured) VALUES ('Bóng Tối Trong Thành Phố', 'bong-toi-trong-thanh-pho', 'Hắc Diệp', 'Thám tử tư Lý Minh nhận vụ điều tra một chuỗi vụ mất tích kỳ lạ. Càng đào sâu, hắn càng nhận ra sự thật đen tối hơn mọi giả thuyết…', 'https://images.unsplash.com/photo-1470813740244-df37b8c1edcb?w=600&h=800&fit=crop', ARRAY['Trinh thám','Kinh dị']::TEXT[], 'ongoing', 20, 420000, false) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.stories (title, slug, author, description, cover_url, genres, status, total_chapters, view_count, is_featured) VALUES ('Vương Gia Thất Nghiệp', 'vuong-gia-that-nghiep', 'Tiểu Bạch', 'Xuyên không thành vương gia nghèo rớt mồng tơi, hắn phải học cách kinh doanh, quản lý phủ đệ và… tán vương phi khó tính của mình.', 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=600&h=800&fit=crop', ARRAY['Hài hước','Lãng mạn']::TEXT[], 'ongoing', 20, 315000, false) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.stories (title, slug, author, description, cover_url, genres, status, total_chapters, view_count, is_featured) VALUES ('Học Viện Phép Thuật Ánh Sao', 'hoc-vien-phep-thuat', 'Star Weaver', 'Ngôi trường bí ẩn giữa bầu trời, nơi những đứa trẻ mang huyết mạch tinh tú tụ hội. Nhưng phía sau vinh quang là một bí mật cổ xưa đang chờ được đánh thức.', 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=600&h=800&fit=crop', ARRAY['Huyền huyễn','Học đường']::TEXT[], 'ongoing', 20, 780000, false) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.stories (title, slug, author, description, cover_url, genres, status, total_chapters, view_count, is_featured) VALUES ('Chiến Thần Tái Sinh', 'chien-than-tai-sinh', 'Long Ẩn', 'Chiến thần thời cổ đại tái sinh trong thân xác một thiếu niên yếu ớt. Bằng ký ức chiến đấu ngàn năm, hắn từng bước leo lên đỉnh cao mới.', 'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?w=600&h=800&fit=crop', ARRAY['Hành động','Huyền huyễn']::TEXT[], 'ongoing', 20, 1580000, false) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.stories (title, slug, author, description, cover_url, genres, status, total_chapters, view_count, is_featured) VALUES ('Quán Cafe Cuối Phố', 'quan-cafe-cuoi-pho', 'Hạ Vy', 'Cô chủ quán cafe nhỏ và vị khách quen bí ẩn luôn gọi cùng một ly latte mỗi 7 giờ tối. Một ngày, anh không đến nữa…', 'https://images.unsplash.com/photo-1502134249126-9f3755a50d78?w=600&h=800&fit=crop', ARRAY['Lãng mạn','Hài hước']::TEXT[], 'ongoing', 20, 234000, false) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.stories (title, slug, author, description, cover_url, genres, status, total_chapters, view_count, is_featured) VALUES ('Tuyệt Thế Võ Thần', 'tuyet-the-vo-than', 'Kiếm Vô Ảnh', 'Từ một tên phế vật bị khinh rẻ, Diệp Thần nhờ vào một cuốn công pháp cổ đại từng bước trở thành võ thần khiến vạn giới run sợ.', 'https://images.unsplash.com/photo-1516339901601-2e1b62dc0c45?w=600&h=800&fit=crop', ARRAY['Hành động','Phiêu lưu']::TEXT[], 'ongoing', 20, 1980000, false) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.stories (title, slug, author, description, cover_url, genres, status, total_chapters, view_count, is_featured) VALUES ('Cô Nàng Kỳ Lạ Nhà Bên', 'co-nang-ky-la', 'Yuki', 'Một ngày nọ, có một cô gái kỳ lạ chuyển đến sống bên cạnh nhà tôi. Cô ấy chỉ xuất hiện vào ban đêm…', 'https://images.unsplash.com/photo-1493246507139-91e8fad9978e?w=600&h=800&fit=crop', ARRAY['Lãng mạn','Hài hước','Học đường']::TEXT[], 'ongoing', 20, 512000, false) ON CONFLICT (slug) DO NOTHING;
INSERT INTO public.stories (title, slug, author, description, cover_url, genres, status, total_chapters, view_count, is_featured) VALUES ('Kẻ Săn Quỷ', 'ke-san-quy', 'Hắc Vũ', 'Thế giới hiện đại nơi quỷ dữ ẩn mình giữa loài người. Một kẻ săn quỷ trẻ tuổi mang lời nguyền tổ tiên bước vào cuộc chiến không hồi kết.', 'https://images.unsplash.com/photo-1447433589675-4aaa569f3e05?w=600&h=800&fit=crop', ARRAY['Kinh dị','Hành động']::TEXT[], 'ongoing', 20, 398000, false) ON CONFLICT (slug) DO NOTHING;

DO $$
DECLARE
  s RECORD;
  c INT;
  paragraphs TEXT;
  ch_title TEXT;
BEGIN
  FOR s IN SELECT id, slug, title FROM public.stories LOOP
    FOR c IN 1..20 LOOP
      ch_title := 'Chương ' || c || ': Hồi thứ ' || c;
      paragraphs :=
        'Gió đêm lạnh lẽo thổi qua từng mái ngói của thành cổ, mang theo mùi hoa quế thoang thoảng. ' || s.title || ' — chương thứ ' || c || ' bắt đầu bằng một tiếng thở dài rất khẽ, như thể cả trời đất cũng đang lắng nghe.' || E'\n\n' ||
        'Nhân vật chính đứng lặng trên đỉnh núi, ánh trăng đổ xuống làm bóng hắn dài trải trên nền đá. Trong lòng hắn, hàng ngàn suy nghĩ đan xen — về quá khứ đã qua, về tương lai chưa tới, và về một bóng hình cứ mãi lởn vởn không rời.' || E'\n\n' ||
        '"Ngươi đã đến rồi sao?" — giọng nói vang lên từ phía sau, trầm ấm và đầy ẩn ý. Hắn không quay lại, chỉ khẽ mỉm cười. Cuộc gặp gỡ này, hắn đã chờ suốt mười năm.' || E'\n\n' ||
        'Trận chiến bắt đầu mà không cần lời cảnh báo. Kiếm khí bay lên tận trời, đá vỡ vụn thành trăm mảnh. Mỗi chiêu thức đều mang theo sát ý ngập trời, nhưng cả hai người đều không hề nao núng.' || E'\n\n' ||
        'Đến khi mặt trời ló dạng ở phía chân trời, mọi thứ mới trở lại yên tĩnh. Trên đỉnh núi giờ chỉ còn lại một người, đứng nhìn về phía bình minh, ánh mắt xa xăm như đang nhớ về một điều gì đó rất xa.' || E'\n\n' ||
        '"Đây mới chỉ là khởi đầu," hắn thì thầm, rồi quay người bước xuống núi. Con đường phía trước còn dài, và câu chuyện của hắn — vẫn chưa kết thúc.' || E'\n\n' ||
        'Trong lúc đó, ở một nơi rất xa, một bóng hình mảnh khảnh đứng bên cửa sổ, tay khẽ chạm vào ô kính lạnh giá. "Chàng ơi, chàng có bình an không?" — câu hỏi tan đi trong sương sớm, không ai đáp lại.' || E'\n\n' ||
        'Câu chuyện của ' || s.title || ' vẫn tiếp diễn, và mỗi trang giấy đều là một mảnh của định mệnh đang dần được hé lộ. Hẹn gặp lại các bạn ở chương tiếp theo.';
      INSERT INTO public.chapters (story_id, chapter_number, title, content, word_count, is_scraped, scraped_at)
      VALUES (s.id, c, ch_title, paragraphs, 320, true, now())
      ON CONFLICT (story_id, chapter_number) DO NOTHING;
    END LOOP;
  END LOOP;
END $$;
