/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TheLoaiRouteImport } from './routes/the-loai'
import { Route as ChanDoanRouteImport } from './routes/chan-doan'
import { Route as CaNhanRouteImport } from './routes/ca-nhan'
import { Route as BangXepHangRouteImport } from './routes/bang-xep-hang'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TruyenSlugRouteImport } from './routes/truyen.$slug'
import { Route as TheLoaiSlugRouteImport } from './routes/the-loai.$slug'
import { Route as TruyenSlugChuongChapterRouteImport } from './routes/truyen.$slug_.chuong.$chapter'

const TheLoaiRoute = TheLoaiRouteImport.update({
  id: '/the-loai',
  path: '/the-loai',
  getParentRoute: () => rootRouteImport,
} as any)
const ChanDoanRoute = ChanDoanRouteImport.update({
  id: '/chan-doan',
  path: '/chan-doan',
  getParentRoute: () => rootRouteImport,
} as any)
const CaNhanRoute = CaNhanRouteImport.update({
  id: '/ca-nhan',
  path: '/ca-nhan',
  getParentRoute: () => rootRouteImport,
} as any)
const BangXepHangRoute = BangXepHangRouteImport.update({
  id: '/bang-xep-hang',
  path: '/bang-xep-hang',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TruyenSlugRoute = TruyenSlugRouteImport.update({
  id: '/truyen/$slug',
  path: '/truyen/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TheLoaiSlugRoute = TheLoaiSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TheLoaiRoute,
} as any)
const TruyenSlugChuongChapterRoute = TruyenSlugChuongChapterRouteImport.update({
  id: '/truyen/$slug_/chuong/$chapter',
  path: '/truyen/$slug/chuong/$chapter',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bang-xep-hang': typeof BangXepHangRoute
  '/ca-nhan': typeof CaNhanRoute
  '/chan-doan': typeof ChanDoanRoute
  '/the-loai': typeof TheLoaiRouteWithChildren
  '/the-loai/$slug': typeof TheLoaiSlugRoute
  '/truyen/$slug': typeof TruyenSlugRoute
  '/truyen/$slug/chuong/$chapter': typeof TruyenSlugChuongChapterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bang-xep-hang': typeof BangXepHangRoute
  '/ca-nhan': typeof CaNhanRoute
  '/chan-doan': typeof ChanDoanRoute
  '/the-loai': typeof TheLoaiRouteWithChildren
  '/the-loai/$slug': typeof TheLoaiSlugRoute
  '/truyen/$slug': typeof TruyenSlugRoute
  '/truyen/$slug/chuong/$chapter': typeof TruyenSlugChuongChapterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bang-xep-hang': typeof BangXepHangRoute
  '/ca-nhan': typeof CaNhanRoute
  '/chan-doan': typeof ChanDoanRoute
  '/the-loai': typeof TheLoaiRouteWithChildren
  '/the-loai/$slug': typeof TheLoaiSlugRoute
  '/truyen/$slug': typeof TruyenSlugRoute
  '/truyen/$slug_/chuong/$chapter': typeof TruyenSlugChuongChapterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/bang-xep-hang'
    | '/ca-nhan'
    | '/chan-doan'
    | '/the-loai'
    | '/the-loai/$slug'
    | '/truyen/$slug'
    | '/truyen/$slug/chuong/$chapter'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/bang-xep-hang'
    | '/ca-nhan'
    | '/chan-doan'
    | '/the-loai'
    | '/the-loai/$slug'
    | '/truyen/$slug'
    | '/truyen/$slug/chuong/$chapter'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/bang-xep-hang'
    | '/ca-nhan'
    | '/chan-doan'
    | '/the-loai'
    | '/the-loai/$slug'
    | '/truyen/$slug'
    | '/truyen/$slug_/chuong/$chapter'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BangXepHangRoute: typeof BangXepHangRoute
  CaNhanRoute: typeof CaNhanRoute
  ChanDoanRoute: typeof ChanDoanRoute
  TheLoaiRoute: typeof TheLoaiRouteWithChildren
  TruyenSlugRoute: typeof TruyenSlugRoute
  TruyenSlugChuongChapterRoute: typeof TruyenSlugChuongChapterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/the-loai': {
      id: '/the-loai'
      path: '/the-loai'
      fullPath: '/the-loai'
      preLoaderRoute: typeof TheLoaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chan-doan': {
      id: '/chan-doan'
      path: '/chan-doan'
      fullPath: '/chan-doan'
      preLoaderRoute: typeof ChanDoanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ca-nhan': {
      id: '/ca-nhan'
      path: '/ca-nhan'
      fullPath: '/ca-nhan'
      preLoaderRoute: typeof CaNhanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bang-xep-hang': {
      id: '/bang-xep-hang'
      path: '/bang-xep-hang'
      fullPath: '/bang-xep-hang'
      preLoaderRoute: typeof BangXepHangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/truyen/$slug': {
      id: '/truyen/$slug'
      path: '/truyen/$slug'
      fullPath: '/truyen/$slug'
      preLoaderRoute: typeof TruyenSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/the-loai/$slug': {
      id: '/the-loai/$slug'
      path: '/$slug'
      fullPath: '/the-loai/$slug'
      preLoaderRoute: typeof TheLoaiSlugRouteImport
      parentRoute: typeof TheLoaiRoute
    }
    '/truyen/$slug_/chuong/$chapter': {
      id: '/truyen/$slug_/chuong/$chapter'
      path: '/truyen/$slug/chuong/$chapter'
      fullPath: '/truyen/$slug/chuong/$chapter'
      preLoaderRoute: typeof TruyenSlugChuongChapterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface TheLoaiRouteChildren {
  TheLoaiSlugRoute: typeof TheLoaiSlugRoute
}

const TheLoaiRouteChildren: TheLoaiRouteChildren = {
  TheLoaiSlugRoute: TheLoaiSlugRoute,
}

const TheLoaiRouteWithChildren =
  TheLoaiRoute._addFileChildren(TheLoaiRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BangXepHangRoute: BangXepHangRoute,
  CaNhanRoute: CaNhanRoute,
  ChanDoanRoute: ChanDoanRoute,
  TheLoaiRoute: TheLoaiRouteWithChildren,
  TruyenSlugRoute: TruyenSlugRoute,
  TruyenSlugChuongChapterRoute: TruyenSlugChuongChapterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
